### ISSUE TITLE
switch to Node.js from Python for the Lambda

### ISSUE THREAD

**Issue by DevenderMusukula** [DevenderMusukula/unit-test-in-pipeline#3]
Nodejs is the in thing right now!!!

**Comment by DevenderMusukula** [comment]
@DevenderMusukula @devendermusukula32

**Comment by devendermusukula32** [comment]
Switching to NodeJs from Python will not give any performance benefit for this usecase.

**Comment by DevenderMusukula** [comment]
Sounds good, let's stick with python for now
